# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.11
loader_version=0.18.4
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version=1.0.2
maven_group=shiny.weightless
archives_base_name=weightless

# Dependencies
fabric_api_version=0.141.2+1.21.11
cca_version=7.3.0
midnightlib_version=1.9.2+1.21.11-fabric
etf_version=7.0.9-fabric-1.21.11
emf_version=3.0.12-fabric-1.21.11